@hostname = localhost
@port = 7089
@host = {{hostname}}:{{port}}/api
@contentType = application/json

#GET https://localhost:7089/api/Articles
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNeVN1YmplY3QiLCJqdGkiOiJkZWYyOTE0ZC1kOTQ3LTQwNDktYjgxMC00OGE1NzEwNjk5ODgiLCJpYXQiOiIwNy8wNC8yMDIyIDE0OjA0OjMwIiwiSWQiOiIxIiwiTG9naW4iOiJ1c2VyIiwiZXhwIjoxNjQ5MzQwODcwLCJpc3MiOiJNeUlzc3VlciIsImF1ZCI6Ik15QXVkaWVuY2UifQ.8HThH2-ibuEsqV7DBU3TGyJ4aepEHoJpCKRqRrD4if4


POST https://localhost:7089/api/AppUser
Content-Type: application/json
{
	"login":"test",
	"password":"test"
}